DELETE FROM Ticket;
DROP TABLE Ticket;
CREATE TABLE Ticket (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    showId INTEGER NOT NULL,
    showName TEXT NOT NULL,
    clientId INTEGER NOT NULL,
    numberOfSeats INTEGER NOT NULL,
    price INTEGER NOT NULL
);
